wget -O jd_bean_change.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bean_change.js
wget -O jd_bean_home.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bean_home.js
wget -O jd_bean_sign.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bean_sign.js
wget -O jd_blueCoin.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_blueCoin.js
wget -O jd_bookshop.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bookshop.js
wget -O jd_car_exchange.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_car_exchange.js
wget -O jd_car.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_car.js
wget -O jd_cash.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_cash.js
wget -O jd_club_lottery.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_club_lottery.js
wget -O jd_coupon.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_coupon.js
wget -O jd_crazy_joy_coin.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_crazy_joy_coin.js
wget -O jd_crazy_joy.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_crazy_joy.js
wget -O jd_daily_egg.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_daily_egg.js
wget -O jd_dreamFactory.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_dreamFactory.js
wget -O jd_family.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_family.js
wget -O jd_festival.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_festival.js
wget -O jd_fruit.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_fruit.js
wget -O jd_get_share_code.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_get_share_code.js
wget -O jd_immortal_answer.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_immortal_answer.js
wget -O jd_immortal.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_immortal.js
wget -O jd_jdfactory.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_jdfactory.js
wget -O jd_jdzz.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_jdzz.js
wget -O jd_joy_feedPets.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy_feedPets.js
wget -O jd_joy_help.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy_help.js
wget -O jd_joy.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy.js
wget -O jd_joy_reward.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy_reward.js
wget -O jd_joy_run.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy_run.js
wget -O jd_joy_steal.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_joy_steal.js
wget -O jd_jxnc.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_jxnc.js
wget -O jd_kd.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_kd.js
wget -O jd_live.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_live.js
wget -O jd_lotteryMachine.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_lotteryMachine.js
wget -O jd_mh.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_mh.js
wget -O jd_moneyTree.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_moneyTree.js
wget -O jd_ms.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_ms.js
wget -O jd_necklace.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_necklace.js
wget -O jd_nh.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nh.js
wget -O jd_nian_ar.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nian_ar.js
wget -O jd_nianCollect.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nianCollect.js
wget -O jd_nian.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nian.js
wget -O jd_nian_sign.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nian_sign.js
wget -O jd_nian_wechat.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_nian_wechat.js
wget -O jd_pet.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_pet.js
wget -O jd_petTreasureBox.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_petTreasureBox.js
wget -O jd_pigPet.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_pigPet.js
wget -O jd_plantBean.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_plantBean.js
wget -O jd_rankingList.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_rankingList.js
wget -O jd_redPacket.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_redPacket.js
wget -O jd_sgmh.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_sgmh.js
wget -O jd_shop.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_shop.js
wget -O jd_small_home.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_small_home.js
wget -O jd_speed.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_speed.js
wget -O jd_super_box.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_super_box.js
wget -O jd_superMarket.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_superMarket.js
wget -O jd_syj.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_syj.js
wget -O jd_unbind.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_unbind.js
wget -O jd_unsubscribe.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_unsubscribe.js
wget -O jd_xg.js https://gitee.com/lxk0301/jd_scripts/raw/master/jd_xg.js
wget -O jx_sign.js https://gitee.com/lxk0301/jd_scripts/raw/master/jx_sign.js