# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-chengdu # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: # 触发器
    - timer: #签到 #签到领现金 #每日抽奖
        parameters:
          name: beansign_cash_dlottery
          cronExpression: "0 5 0,12,18 * * * *"
          enable: true
          argument: jd_bean_sign&jd_cash&jd_daily_lottery
    - timer: #京小超兑换奖品 #京东汽车兑换
        parameters:
          name: blueCoin_carexc
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_blueCoin&jd_car_exchange
    - timer: #东东农场 #东东萌宠 #口袋书店 #金榜创造营 #明星小店 #大老板 #pk #京喜农场(cancel)
        parameters:
          name: fruit_pet_bookshop_gcreator_starshop_pk #_jxnc
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_gold_creator&jd_star_shop&jd_wsdlb&jd_ddopk # &jd_jxnc
    - timer: # 宠汪汪# 摇钱树# 京东种豆得豆# 京喜工厂 #东东工厂
        parameters:
          name: joy_mTree_plantBean_dFactory_jdfactory
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_joy_new
    - timer: #宠汪汪积分兑换奖品 #点点券 #东东小窝 #京喜财富岛
        parameters:
          name: joy_reward_necklace_smlhome_cfd
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_small_home&jd_cfd&jd_necklace&jd_necklace_new&jd_joy_reward_new
    - timer: #京东全民开红包 #进店领豆 #取关京东店铺商品 #京东汽车 #京东秒秒币 #领金贴
        parameters:
          name: redPacket_shop_unsub_car_ms_jtie
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_car&jd_jin_tie&jd_bean_sign&jd_ms
    - timer: #京东天天加速 #京喜牧场 #电竞经理
        parameters:
          name: speed_jxmc_em
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_speed&jd_jxmc&jd_EsportsManager
    - timer: #东东超市 #十元街 #翻翻乐
        parameters:
          name: superMarket_syj_winner
          cronExpression: "0 15 * * * * *"
          enable: true
          argument: jd_superMarket&jd_syj #&jd_big_winner
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #闪购盲盒 #Joy分红 #京东保价
        parameters:
          name: bchg_cjoy_rList_bhome_sgmh_cjoybonus_price
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_sgmh&jd_crazy_joy_bonus&jd_price
    - timer: #金融养猪 #京东快递 #京东赚赚
        parameters:
          name: pigPet_kd_jdzz
          cronExpression: "0 3 1 * * * *"
          enable: true
          argument: jd_pigPet&jd_kd&jd_jdzz
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
