# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-chengdu # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 3600 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  installDependency: true # 是否在线安装依赖 
  events: # 触发器
    - timer: #签到 #领现金
        parameters:
          name: beansign_cash
          cronExpression: "0 5 0,12,18 * * * *"
          enable: true
          argument: jd_bean_sign&jd_cash
    - timer: #京小超兑换 #财富岛提现 #京东汽车兑换 #宠汪汪兑换 
        parameters:
          name: blueCoin_cfdtx_carexc_joyrw
          cronExpression: "0 59 7,11,12,15,23 * * * *"
          enable: true
          argument: jd_blueCoin&jd_car_exchange&jd_joy_reward #&jd_cfdtx
    - timer: #东东农场 #东东萌宠 #口袋书店 #金榜创造营 #大老板 #京喜农场(cancel)
        parameters:
          name: fruit_pet_bshop_gcreator_dlb #_jxnc
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_gold_creator&jd_wsdlb # &jd_jxnc
    - timer: #摇钱树 #京东种豆 #京喜工厂 #东东工厂 #到家鲜豆庄园收水滴 ###宠汪汪喂食
        parameters:
          name: mTree_pBean_jxFac_jdfac_joyfd_djgp
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jddj_getPoints  #&jd_joy_feedPets
    - timer: #东东小窝 #点点券 #电竞经理 #零食街 #健康社区 #到家果园 ###美妆 #跳跳乐
        parameters:
          name: shome_neckl_jp_em_fr_bt_hlth_djf
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_small_home&jd_esManager&jd_foodRunning&jd_necklace&jd_health&jddj_fruit #&jd_beauty&jd_jump
    - timer: #全民开红包 #进店领豆 #取关店铺商品 #京东汽车 #京东秒秒币 #领金贴 #京喜签到[AL] #领券中心签到 #到家鲜豆
        parameters:
          name: redP_shop_unsub_car_ms_jtie_jxqd_cs_djb
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_car&jd_jin_tie&jd_ms&jd_jxqd&jd_ccSign&jddj_bean
    - timer: #京东天天加速 #京喜牧场 #宠汪汪偷狗粮 #宠汪汪
        parameters:
          name: speed_jxmc_joystl_joy
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_speed&jd_jxmc&jd_joy_steal&jd_joy
    - timer: #东东超市 #十元街 #财富岛 #翻翻乐 #到家果园收水滴
        parameters:
          name: superMarket_syj_cfd_ffl_djfc
          cronExpression: "0 15 * * * * *"
          enable: true
          argument: jd_superMarket&jd_syj&jd_cfd&jd_big_winner&jd_health_energy&jddj_fruit_collectWater
    - timer: #京豆变动通知 #京东排行榜 #领京豆额外奖励 #闪购盲盒 #京东保价 #京喜签到[HW] #粉丝互动 #女装盲盒 ###价格保护 
        parameters:
          name: bchg_rList_bhome_sgmh_jxs_wxfan_nzmh #_price
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_rankingList&jd_bean_home&jd_sgmh&jx_sign&jd_wxFans&jd_nzmh #&jd_price
    - timer: #金融养猪 #京东快递 #京东赚赚 #极速版签到 #抽奖机 #许愿池 #取关直播 #到家鲜豆庄园
        parameters:
          name: pigPet_kd_jdzz_ssign_lMach_wish_usl_djpb
          cronExpression: "0 23 0 * * * *"
          enable: true
          argument: jd_pigPet&jd_kd&jd_jdzz&jd_speed_sign&jd_lotteryMachine&jd_wish&z_cfd&jd_unsubLive&jddj_plantBeans
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
